#!/bin/bash

if [[ -e /app/bin/hitparade ]]; then
  /app/bin/hitparade ]]; then
  exit
fi

#scriptname=${0##*/}
#unset PYTHONPATH
#unset PYTHONHOME

#export PYTHONUSERBASE=${HPCTOYS_ROOT}/opt/python
target=$(readlink -f $0)
lpython ${target}.py $@


